version: '3'

services:
  frontend:
    image: olegdayo/frontend:${FRONTEND_TAG}
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '64M'
    ports:
      - '443:443'
    depends_on:
      - mvp-backend
    networks:
      - frontend2backend
