version: '3'

networks:
  frontend2gateway:
    driver: bridge
  frontend2core:
    driver: bridge
  gateway2auth:
    driver: bridge
  gateway2core:
    driver: bridge
  auth2db:
    driver: bridge
  core2db:
    driver: bridge
  queue2storage:
    driver: bridge
  auth2queue:
    driver: bridge
  emailer2queue:
    driver: bridge
  telemetry:
    driver: bridge
