version: '3'

services:
  # Monitor module
  ceph-mon:
    # Mirror has been downloaded to harbor private server
    image: ceph/daemon:latest
    network_mode: host
    container_name: ceph-mon
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /srv/ceph/etc_ceph:/etc/ceph
      - /srv/ceph/var_lib_ceph:/var/lib/ceph
    environment:
      # The current server IP, don't forget to change the IP when deploying on different servers
      MON_IP: 192.168.0.20
      CEPH_PUBLIC_NETWORK: 192.168.0.0/24
    command: mon

  # Deploy Manager daemon module
  ceph-mgr:
    image: ceph/daemon:latest
    network_mode: host
    container_name: ceph-mgr
    restart: always
    depends_on:
      - ceph-mon
    volumes:
      - /etc/localtime:/etc/localtime
      - /srv/ceph/etc_ceph:/etc/ceph
      - /srv/ceph/var_lib_ceph:/var/lib/ceph
    command: mgr # && ceph mgr module enable dashboard

  # OSD module
  ceph-osd:
    image: ceph/daemon:latest
    network_mode: host
    container_name: ceph-osd
    restart: always
    privileged: true
    # Share the process namespace with the host system. Containers with this option turned on can access and operate on each other through the process ID.
    pid: host
    depends_on:
      - ceph-mgr
    volumes:
      - /etc/localtime:/etc/localtime
      - /srv/ceph/etc_ceph:/etc/ceph
      - /srv/ceph/var_lib_ceph:/var/lib/ceph
    command: osd_directory

  # # MDS module (used to support CephFS file system storage, selected according to actual situation, not required)
  # ceph-mds:
  #   image: ceph/daemon:latest
  #   network_mode: host
  #   container_name: ceph-mds
  #   restart: always
  #   depends_on:
  #     - ceph-osd
  #   volumes:
  #     - /etc/localtime:/etc/localtime
  #     - /srv/ceph/etc_ceph:/etc/ceph
  #     - /srv/ceph/var_lib_ceph:/var/lib/ceph
  #   environment:
  #     # 0 means no automatic file system creation (recommended), 1 means automatic creation
  #     CEPHFS_CREATE: 1
  #   command: mds
