version: '3'

services:
  auth:
    image: olegdayo/auth:${AUTH_TAG}
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '64M'
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - gateway2auth
      - auth2db

  core:
    image: olegdayo/auth:${CORE_TAG}
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '64M'
    depends_on:
      core-db:
        condition: service_healthy
      # core-s3:
      #   condition: service_healthy
    networks:
      - gateway2core
      - core2db
      - core2s3

  gateway:
    image: olegdayo/gateway:${GATEWAY_TAG}
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '64M'
    depends_on:
      - auth
      - core
    networks:
      - gateway2auth
      - gateway2core
