version: '3'

services:
  auth:
    image: olegdayo/auth:${AUTH_TAG}
    command: ["./auth.yaml"]
    ports:
      - '8081:8080'
    volumes:
      - './configs/auth.yaml:/app/auth.yaml'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '64M'
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - gateway2auth
      - auth2db

  core:
    image: olegdayo/core:${CORE_TAG}
    command: ["./core.yaml"]
    ports:
      - '8082:8080'
    volumes:
      - './configs/core.yaml:/app/core.yaml'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '64M'
    depends_on:
      core-db:
        condition: service_healthy
      # core-s3:
      #   condition: service_healthy
    networks:
      - frontend2core
      - gateway2core
      - core2db

  gateway:
    image: olegdayo/gateway:${GATEWAY_TAG}
    command: ["./gateway.yaml"]
    ports:
      - '8080:8080'
    volumes:
      - './configs/gateway.yaml:/app/gateway.yaml'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '64M'
    depends_on:
      - auth
      - core
    networks:
      - gateway2auth
      - gateway2core
      - frontend2gateway
