version: '3'

services:
  mvp-db:
    image: postgres:15.1
    hostname: mvp-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: graphs
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - mvp-data:/var/lib/postgresql/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d graphs" ]
      interval: 5s
      timeout: 5s
      retries: 100
      start_period: 10s
    networks:
      - backend2db

volumes:
  mvp-data:
