version: '3'

services:
  frontend:
    image: olegdayo/frontend:${FRONTEND_TAG}
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '64M'
    volumes:
      - /opt/nginx/ssl:/etc/nginx/ssl
    ports:
      - '443:443'
    depends_on:
      - gateway
    networks:
      - frontend2gateway
