version: '3'

networks:
  frontend2gateway:
    driver: bridge
  gateway2auth:
    driver: bridge
  gateway2core:
    driver: bridge
  auth2db:
    driver: bridge
  core2db:
    driver: bridge
  core2s3:
    driver: bridge
