port: 8080

db:
  schema: "postgres"
  user: "user"
  password: "password"
  ip: "core-db"
  port: 5432
  database: "db"
  ssl: "disable"
  migrations_path: "github://hse-telescope/core/migrations"

clients:
  example:
    url: http://localhost:8080

logger:
  mode: info
