port: 8080

clients:
  auth:
    url: http://auth:8080
  core:
    url: http://core:8080

public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwOeFttt1KsCR/Ae/DBCm3W9uHVmL4YCXtEUJtbDnfeuJcxWLfgKvXDTO45BOdZ+yoJzGAOkJu0DkGcBobXOPLRSleWgwSAzzYfEL8NvYORo6Pg/E5rZuTkZWwMUdKfHXKZGm8wSW9eVhVtpN+Yg4r7fNbXfV+jppmI4VztPGwkeVLVDHD9X7OkIvfgyLxeefNKpIuNdB2xO01zq2+Ph60jSh6BfcSdzLxP7KjWPzHReg+R55vtPpFHTO1+K+uGp1HEn4uA37DJtBOSOd909MsF03Zohi5kk8A+HHHoL7CFxg0CRQzYiGnBXvCAQvUWhOKATxo89QzoUTzQdUwJO2QqGBxJjRiHDLer5kprdgkAEcS0jKNR0G4a9xDPmkJ8y1n57afqNRZQF3d/6F3DJOBK8dKMDEaqYZWfiiUYcOSlzS95RSWs9GJKeoNbDDmJfMq/9EW/gNcMFUHl96ZElWgowjDoJaBgviJ1sK4I/hBrvANLH/458TotrA4qjV2Jh8= olegsidorenkov@MacBookPro

logger:
  mode: staging
