global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090

  - job_name: auth-service
    static_configs:
      - targets:
        - auth:8080

  - job_name: core-service
    static_configs:
      - targets:
        - core:8080

  - job_name: emailer-service
    static_configs:
      - targets:
        - emailer:8080

  - job_name: gateway-service
    static_configs:
      - targets:
        - gateway:8080

  - job_name: auth-db-exporter
    static_configs:
      - targets:
        - auth-db-exporter:9187

  - job_name: core-db-exporter
    static_configs:
      - targets:
        - core-db-exporter:9187
