apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: olegdayo/auth:33b6ae61db666d8821982111c609dc94606a3bd1 # TODO: replace version
          # command: ["./auth"]
          args: ["./auth.yaml"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: 'config-volume'
              mountPath: '/app/auth.yaml'
          resources:
            requests:
              memory: '64MB'
              cpu: '0.2'
            limits:
              memory: '64MB'
              cpu: '0.2'
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
      volumes:
        - name: 'config-volume'
          configMap:
            name: 'auth-config-map'
